// Code generated by protoc-gen-go. DO NOT EDIT.
// source: download.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Download struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContentLength        int64    `protobuf:"varint,2,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	BytesDownloaded      int64    `protobuf:"varint,4,opt,name=bytes_downloaded,json=bytesDownloaded,proto3" json:"bytes_downloaded,omitempty"`
	Done                 bool     `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Download) Reset()         { *m = Download{} }
func (m *Download) String() string { return proto.CompactTextString(m) }
func (*Download) ProtoMessage()    {}
func (*Download) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{0}
}
func (m *Download) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Download.Unmarshal(m, b)
}
func (m *Download) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Download.Marshal(b, m, deterministic)
}
func (m *Download) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Download.Merge(m, src)
}
func (m *Download) XXX_Size() int {
	return xxx_messageInfo_Download.Size(m)
}
func (m *Download) XXX_DiscardUnknown() {
	xxx_messageInfo_Download.DiscardUnknown(m)
}

var xxx_messageInfo_Download proto.InternalMessageInfo

func (m *Download) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Download) GetContentLength() int64 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *Download) GetBytesDownloaded() int64 {
	if m != nil {
		return m.BytesDownloaded
	}
	return 0
}

func (m *Download) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type DownloadList struct {
	DownloadItem         []*Download `protobuf:"bytes,1,rep,name=download_item,json=downloadItem,proto3" json:"download_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DownloadList) Reset()         { *m = DownloadList{} }
func (m *DownloadList) String() string { return proto.CompactTextString(m) }
func (*DownloadList) ProtoMessage()    {}
func (*DownloadList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{1}
}
func (m *DownloadList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadList.Unmarshal(m, b)
}
func (m *DownloadList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadList.Marshal(b, m, deterministic)
}
func (m *DownloadList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadList.Merge(m, src)
}
func (m *DownloadList) XXX_Size() int {
	return xxx_messageInfo_DownloadList.Size(m)
}
func (m *DownloadList) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadList.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadList proto.InternalMessageInfo

func (m *DownloadList) GetDownloadItem() []*Download {
	if m != nil {
		return m.DownloadItem
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{2}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Download)(nil), "protobuf.Download")
	proto.RegisterType((*DownloadList)(nil), "protobuf.DownloadList")
	proto.RegisterType((*Void)(nil), "protobuf.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DownloadsClient is the client API for Downloads service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownloadsClient interface {
	Add(ctx context.Context, in *Download, opts ...grpc.CallOption) (*Download, error)
	List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*DownloadList, error)
}

type downloadsClient struct {
	cc *grpc.ClientConn
}

func NewDownloadsClient(cc *grpc.ClientConn) DownloadsClient {
	return &downloadsClient{cc}
}

func (c *downloadsClient) Add(ctx context.Context, in *Download, opts ...grpc.CallOption) (*Download, error) {
	out := new(Download)
	err := c.cc.Invoke(ctx, "/protobuf.Downloads/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadsClient) List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*DownloadList, error) {
	out := new(DownloadList)
	err := c.cc.Invoke(ctx, "/protobuf.Downloads/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadsServer is the server API for Downloads service.
type DownloadsServer interface {
	Add(context.Context, *Download) (*Download, error)
	List(context.Context, *Void) (*DownloadList, error)
}

func RegisterDownloadsServer(s *grpc.Server, srv DownloadsServer) {
	s.RegisterService(&_Downloads_serviceDesc, srv)
}

func _Downloads_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Download)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Downloads/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadsServer).Add(ctx, req.(*Download))
	}
	return interceptor(ctx, in, info, handler)
}

func _Downloads_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Downloads/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadsServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Downloads_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Downloads",
	HandlerType: (*DownloadsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Downloads_Add_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Downloads_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "download.proto",
}

func init() { proto.RegisterFile("download.proto", fileDescriptor_f7ce52b48c9eea83) }

var fileDescriptor_f7ce52b48c9eea83 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xb1, 0x4b, 0x03, 0x31,
	0x14, 0xc6, 0x89, 0x09, 0xe5, 0xfa, 0x6c, 0xcf, 0xf2, 0x06, 0x09, 0x9d, 0xc2, 0x81, 0x10, 0x07,
	0x33, 0xd4, 0xc1, 0x59, 0x28, 0x88, 0xd0, 0x29, 0x83, 0xeb, 0xe1, 0x99, 0xa8, 0x27, 0xd7, 0x44,
	0x7a, 0xaf, 0x88, 0xab, 0x7f, 0xb9, 0x5c, 0xb8, 0xe8, 0xd0, 0x9b, 0xf2, 0xf8, 0xbd, 0x5f, 0xbe,
	0xf7, 0x41, 0xe9, 0xe2, 0x57, 0xe8, 0xe2, 0xb3, 0x33, 0x9f, 0x87, 0x48, 0x11, 0x8b, 0xf4, 0x34,
	0xc7, 0xd7, 0xea, 0x87, 0x41, 0xb1, 0x1d, 0x97, 0xb8, 0x02, 0x7e, 0x3c, 0x74, 0x92, 0x29, 0xa6,
	0xe7, 0x76, 0x18, 0xf1, 0x0a, 0xca, 0x97, 0x18, 0xc8, 0x07, 0xaa, 0x3b, 0x1f, 0xde, 0xe8, 0x5d,
	0x9e, 0x29, 0xa6, 0xb9, 0x5d, 0x8e, 0x74, 0x97, 0x20, 0x5e, 0xc3, 0xaa, 0xf9, 0x26, 0xdf, 0xd7,
	0xf9, 0x8e, 0x77, 0x52, 0x24, 0xf1, 0x22, 0xf1, 0xed, 0x1f, 0x46, 0x04, 0xe1, 0x62, 0xf0, 0x92,
	0x2b, 0xa6, 0x0b, 0x9b, 0xe6, 0xea, 0x01, 0x16, 0xd9, 0xd8, 0xb5, 0x3d, 0xe1, 0x1d, 0x2c, 0x73,
	0x50, 0xdd, 0x92, 0xdf, 0x4b, 0xa6, 0xb8, 0x3e, 0xdf, 0xa0, 0xc9, 0xb5, 0x4d, 0xd6, 0xed, 0x22,
	0x8b, 0x8f, 0xe4, 0xf7, 0xd5, 0x0c, 0xc4, 0x53, 0x6c, 0xdd, 0xe6, 0x03, 0xe6, 0xd9, 0xe8, 0xf1,
	0x06, 0xf8, 0xbd, 0x73, 0x38, 0xf1, 0x7b, 0x3d, 0xc1, 0xd0, 0x80, 0x48, 0x25, 0xca, 0xff, 0xdd,
	0x90, 0xb9, 0xbe, 0x3c, 0x75, 0x07, 0xaf, 0x99, 0x25, 0x7c, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0xae, 0xee, 0x84, 0xaf, 0x64, 0x01, 0x00, 0x00,
}
